name: create-release
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: [self-hosted, macOS]    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Detect version
      uses: FLORG1/github-version-action@v1
      with:
        var-name: TAG_VERSION        

    - name: Build
      run: export TAG_VERSION; ./build.sh
    
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        prerelease: true
        allowUpdates: true
        replacesArtifacts: true
        artifacts: "Nimble.dmg"
        token: ${{ secrets.GITHUB_TOKEN }}