name: create-release
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: self-hosted    
    steps:
    - id: get_version
      uses: battila7/get-version-action@v2

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive      

    - name: Build
      run: ./archive-sign.sh Nimble Nimble-Archive Nimble NimblePlugins-Archive ./Nimble/Nimble/exportOptionsPlist.plist ./Nimble/Nimble/Nimble.entitlements
      env:
        DEVELOPER_ID: ${{ secrets.APPLE_DEVELOPER_ID }}
        AC_USERNAME: ${{ secrets.APPLE_DEVELOPER_USERNAME }}
        AC_PASSWORD: ${{ secrets.APPLE_ALTOOL_PASSWORD }}
        PROVIDER_SHORTNAME: ${{ secrets.APPLE_DEVELOPER_SHORTNAME }}
        TAG_VERSION: ${{ steps.get_version.outputs.version-without-v }}
    
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        prerelease: true
        allowUpdates: true
        replacesArtifacts: true
        artifacts: "ArchiveDir/Nimble.dmg"
        token: ${{ secrets.GITHUB_TOKEN }}
