name: pull-request
on:
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: [self-hosted, macOS]    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build
      run: ./build.sh              
    
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Nimble.dmg
        path: ./Nimble.dmg